### ISSUE TITLE
The dependency "thecodingmachine/safe" generates deprecated logs in PHP 8.4.

### ISSUE THREAD

**Issue by martio** [laragraph/utils#19]
The dependency "thecodingmachine/safe" generates deprecated logs in PHP 8.4.

Please update the dependency "thecodingmachine/safe" to "dev-master".

<img width="1510" alt="Screenshot" src="https://github.com/user-attachments/assets/fa82f055-8d58-4d49-9755-453f8e362c77" />

**Comment by spawnia** [comment]
We will stick with requiring tagged releases. Feel free to post a pull request when v3 is available.
