### ISSUE TITLE
header with ContentType Error

### ISSUE THREAD

**Issue by Ferikl** [laragraph/utils#5]
With latest version had an error: 
GraphQL\Server\RequestError
Unexpected content type: "application/json;charset=UTF-8"

In previous version there is no such error
I think its related with new header parser: [https://github.com/laragraph/utils/commit/c66d3b8257f6a5e77910caf314d5a47189884fb8](https://github.com/laragraph/utils/commit/c66d3b8257f6a5e77910caf314d5a47189884fb8)

**Steps to reproduce**

1.Send normal request with header: Content-Type: application/json;charset=UTF-8.

**Output/Logs**

/vendor/laragraph/utils/src/RequestParser.php in Laragraph\Utils\RequestParser::parseRequest at line 72

```
# GraphQL\Server\RequestError
# Unexpected content type: "application/json;charset=UTF-8"
# /vendor/laragraph/utils/src/RequestParser.php in Laragraph\Utils\RequestParser::parseRequest at line 72

```

</details></br>

**Comment by spawnia** [comment]
I added proper regression tests and fixed this for all content types, released with https://github.com/laragraph/utils/releases/tag/v1.1.1
