### ISSUE TITLE
`TransformsRequest` middlewares are ignored 

### ISSUE THREAD

**Issue by LastDragon-ru** [laragraph/utils#9]
For json requests the `RequestParser` use

https://github.com/laragraph/utils/blob/7d6b247e2db4e1c9f5988bcb80ed9d3eda70ce23/src/RequestParser.php#L54-L55

that return raw data. This is why `ConvertEmptyStringsToNull` doesn't work in Lightouse (https://github.com/nuwave/lighthouse/issues/1459). All other `TransformsRequest` middlewares probably also ignored.

For Laravel v9 (not sure about v8 and below, sorry) and JSON requests it seems can be solved by:

```php
                /** @var string $content */
                // $content = $request->getContent();
                // $bodyParams = \Safe\json_decode($content, true);
                $bodyParams = $request->json()?->all(); // <-- fix
```

PS: v1.3.0

**Comment by spawnia** [comment]
Open for pull requests.

**Comment by spawnia** [comment]
I think this is resolved by https://github.com/nuwave/lighthouse/pull/2123, let me know if you think otherwise.

**Comment by LastDragon-ru** [comment]
I think PR is fine, thank you.
